{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "e33c038b-3c5b-4fd8-9e56-8bed5fc5c470",
   "metadata": {},
   "outputs": [],
   "source": [
    "import numpy as np\n",
    "import pandas as pd\n",
    "\n",
    "import matplotlib.pyplot as plt\n",
    "\n",
    "from sklearn.preprocessing import StandardScaler\n",
    "from sklearn.preprocessing import LabelEncoder, OrdinalEncoder, OneHotEncoder\n",
    "from sklearn.model_selection import train_test_split\n",
    "from sklearn.metrics import classification_report, accuracy_score\n",
    "from sklearn.ensemble import RandomForestClassifier\n",
    "from sklearn.linear_model import LogisticRegression\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "1d4dd121-3ca0-438c-8488-32abaaa93bfd",
   "metadata": {},
   "outputs": [],
   "source": [
    "data = pd.read_csv('unclean depress1.csv')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "c06189c0-ffb1-4209-af22-0f4d7111f838",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Number</th>\n",
       "      <th>Sleep</th>\n",
       "      <th>Appetite</th>\n",
       "      <th>Interest</th>\n",
       "      <th>Fatigue</th>\n",
       "      <th>Worthlessness</th>\n",
       "      <th>Concentration</th>\n",
       "      <th>Agitation</th>\n",
       "      <th>Suicidal Ideation</th>\n",
       "      <th>Sleep Disturbance</th>\n",
       "      <th>Aggression</th>\n",
       "      <th>Panic Attacks</th>\n",
       "      <th>Hopelessness</th>\n",
       "      <th>Restlessness</th>\n",
       "      <th>Low Energy</th>\n",
       "      <th>Depression State</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>1</td>\n",
       "      <td>Less than 3 hours</td>\n",
       "      <td>Significantly decreased</td>\n",
       "      <td>I still find joy in my activities</td>\n",
       "      <td>I am frequently exhausted and struggle to get ...</td>\n",
       "      <td>I frequently feel like a failure and question ...</td>\n",
       "      <td>I focus easily and stay engaged</td>\n",
       "      <td>I am frequently overwhelmed by restlessness an...</td>\n",
       "      <td>Pretty much daily</td>\n",
       "      <td>Sleep like a baby</td>\n",
       "      <td>Angry almost every day</td>\n",
       "      <td>Almost every day, out of nowhere</td>\n",
       "      <td>Always – I feel hopeless every day</td>\n",
       "      <td>I constantly feel uneasy or on edge</td>\n",
       "      <td>I frequently feel completely exhausted and inc...</td>\n",
       "      <td>Mild</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>2</td>\n",
       "      <td>3–5 hours</td>\n",
       "      <td>Significantly increased</td>\n",
       "      <td>I feel completely disengaged and indifferent t...</td>\n",
       "      <td>I feel energized and capable most of the time</td>\n",
       "      <td>I generally feel confident and worthwhile</td>\n",
       "      <td>Concentration is almost impossible, and I feel...</td>\n",
       "      <td>I feel calm and settled</td>\n",
       "      <td>Never</td>\n",
       "      <td>Barely sleep at all anymore</td>\n",
       "      <td>Very calm</td>\n",
       "      <td>Never happens</td>\n",
       "      <td>Almost never – I usually feel hopeful</td>\n",
       "      <td>I feel calm most of the time</td>\n",
       "      <td>I usually feel energized and motivated through...</td>\n",
       "      <td>Moderate</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>3</td>\n",
       "      <td>More than 9 hours</td>\n",
       "      <td>Slightly decreased</td>\n",
       "      <td>I notice a dulling of interest sometimes</td>\n",
       "      <td>I sometimes feel drained but manage</td>\n",
       "      <td>I occasionally doubt myself</td>\n",
       "      <td>Distractions sometimes interfere with my focus</td>\n",
       "      <td>I sometimes feel restless or fidgety</td>\n",
       "      <td>Once in a blue moon</td>\n",
       "      <td>Occasionally toss and turn</td>\n",
       "      <td>A little irritated sometimes</td>\n",
       "      <td>Rarely, maybe once or twice</td>\n",
       "      <td>Sometimes – I feel stuck now and then</td>\n",
       "      <td>It happens, but not often</td>\n",
       "      <td>I sometimes feel a bit tired, but it doesn't a...</td>\n",
       "      <td>Severe</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>4</td>\n",
       "      <td>Less than 3 hours</td>\n",
       "      <td>Significantly decreased</td>\n",
       "      <td>I still find joy in my activities</td>\n",
       "      <td>I am frequently exhausted and struggle to get ...</td>\n",
       "      <td>I frequently feel like a failure and question ...</td>\n",
       "      <td>I focus easily and stay engaged</td>\n",
       "      <td>I am frequently overwhelmed by restlessness an...</td>\n",
       "      <td>Pretty much daily</td>\n",
       "      <td>Sleep like a baby</td>\n",
       "      <td>Angry almost every day</td>\n",
       "      <td>Almost every day, out of nowhere</td>\n",
       "      <td>Always – I feel hopeless every day</td>\n",
       "      <td>I constantly feel uneasy or on edge</td>\n",
       "      <td>I frequently feel completely exhausted and inc...</td>\n",
       "      <td>No depression</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>5</td>\n",
       "      <td>3–5 hours</td>\n",
       "      <td>Significantly increased</td>\n",
       "      <td>I feel completely disengaged and indifferent t...</td>\n",
       "      <td>I feel energized and capable most of the time</td>\n",
       "      <td>I generally feel confident and worthwhile</td>\n",
       "      <td>Concentration is almost impossible, and I feel...</td>\n",
       "      <td>I feel calm and settled</td>\n",
       "      <td>Never</td>\n",
       "      <td>Barely sleep at all anymore</td>\n",
       "      <td>Very calm</td>\n",
       "      <td>Never happens</td>\n",
       "      <td>Almost never – I usually feel hopeful</td>\n",
       "      <td>I feel calm most of the time</td>\n",
       "      <td>I usually feel energized and motivated through...</td>\n",
       "      <td>Moderate</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>808</th>\n",
       "      <td>809</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>809</th>\n",
       "      <td>810</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>810</th>\n",
       "      <td>811</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>811</th>\n",
       "      <td>812</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>812</th>\n",
       "      <td>813</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>813 rows × 16 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "     Number               Sleep                 Appetite  \\\n",
       "0          1  Less than 3 hours  Significantly decreased   \n",
       "1          2          3–5 hours  Significantly increased   \n",
       "2          3  More than 9 hours       Slightly decreased   \n",
       "3          4  Less than 3 hours  Significantly decreased   \n",
       "4          5          3–5 hours  Significantly increased   \n",
       "..       ...                ...                      ...   \n",
       "808      809                NaN                      NaN   \n",
       "809      810                NaN                      NaN   \n",
       "810      811                NaN                      NaN   \n",
       "811      812                NaN                      NaN   \n",
       "812      813                NaN                      NaN   \n",
       "\n",
       "                                              Interest  \\\n",
       "0                    I still find joy in my activities   \n",
       "1    I feel completely disengaged and indifferent t...   \n",
       "2             I notice a dulling of interest sometimes   \n",
       "3                    I still find joy in my activities   \n",
       "4    I feel completely disengaged and indifferent t...   \n",
       "..                                                 ...   \n",
       "808                                                NaN   \n",
       "809                                                NaN   \n",
       "810                                                NaN   \n",
       "811                                                NaN   \n",
       "812                                                NaN   \n",
       "\n",
       "                                               Fatigue  \\\n",
       "0    I am frequently exhausted and struggle to get ...   \n",
       "1        I feel energized and capable most of the time   \n",
       "2                  I sometimes feel drained but manage   \n",
       "3    I am frequently exhausted and struggle to get ...   \n",
       "4        I feel energized and capable most of the time   \n",
       "..                                                 ...   \n",
       "808                                                NaN   \n",
       "809                                                NaN   \n",
       "810                                                NaN   \n",
       "811                                                NaN   \n",
       "812                                                NaN   \n",
       "\n",
       "                                         Worthlessness  \\\n",
       "0    I frequently feel like a failure and question ...   \n",
       "1            I generally feel confident and worthwhile   \n",
       "2                          I occasionally doubt myself   \n",
       "3    I frequently feel like a failure and question ...   \n",
       "4            I generally feel confident and worthwhile   \n",
       "..                                                 ...   \n",
       "808                                                NaN   \n",
       "809                                                NaN   \n",
       "810                                                NaN   \n",
       "811                                                NaN   \n",
       "812                                                NaN   \n",
       "\n",
       "                                         Concentration  \\\n",
       "0                      I focus easily and stay engaged   \n",
       "1    Concentration is almost impossible, and I feel...   \n",
       "2       Distractions sometimes interfere with my focus   \n",
       "3                      I focus easily and stay engaged   \n",
       "4    Concentration is almost impossible, and I feel...   \n",
       "..                                                 ...   \n",
       "808                                                NaN   \n",
       "809                                                NaN   \n",
       "810                                                NaN   \n",
       "811                                                NaN   \n",
       "812                                                NaN   \n",
       "\n",
       "                                             Agitation    Suicidal Ideation  \\\n",
       "0    I am frequently overwhelmed by restlessness an...    Pretty much daily   \n",
       "1                              I feel calm and settled                Never   \n",
       "2                 I sometimes feel restless or fidgety  Once in a blue moon   \n",
       "3    I am frequently overwhelmed by restlessness an...    Pretty much daily   \n",
       "4                              I feel calm and settled                Never   \n",
       "..                                                 ...                  ...   \n",
       "808                                                NaN                  NaN   \n",
       "809                                                NaN                  NaN   \n",
       "810                                                NaN                  NaN   \n",
       "811                                                NaN                  NaN   \n",
       "812                                                NaN                  NaN   \n",
       "\n",
       "               Sleep Disturbance                    Aggression  \\\n",
       "0              Sleep like a baby        Angry almost every day   \n",
       "1    Barely sleep at all anymore                     Very calm   \n",
       "2     Occasionally toss and turn  A little irritated sometimes   \n",
       "3              Sleep like a baby        Angry almost every day   \n",
       "4    Barely sleep at all anymore                     Very calm   \n",
       "..                           ...                           ...   \n",
       "808                          NaN                           NaN   \n",
       "809                          NaN                           NaN   \n",
       "810                          NaN                           NaN   \n",
       "811                          NaN                           NaN   \n",
       "812                          NaN                           NaN   \n",
       "\n",
       "                        Panic Attacks                           Hopelessness  \\\n",
       "0    Almost every day, out of nowhere     Always – I feel hopeless every day   \n",
       "1                       Never happens  Almost never – I usually feel hopeful   \n",
       "2         Rarely, maybe once or twice  Sometimes – I feel stuck now and then   \n",
       "3    Almost every day, out of nowhere     Always – I feel hopeless every day   \n",
       "4                       Never happens  Almost never – I usually feel hopeful   \n",
       "..                                ...                                    ...   \n",
       "808                               NaN                                    NaN   \n",
       "809                               NaN                                    NaN   \n",
       "810                               NaN                                    NaN   \n",
       "811                               NaN                                    NaN   \n",
       "812                               NaN                                    NaN   \n",
       "\n",
       "                            Restlessness  \\\n",
       "0    I constantly feel uneasy or on edge   \n",
       "1           I feel calm most of the time   \n",
       "2              It happens, but not often   \n",
       "3    I constantly feel uneasy or on edge   \n",
       "4           I feel calm most of the time   \n",
       "..                                   ...   \n",
       "808                                  NaN   \n",
       "809                                  NaN   \n",
       "810                                  NaN   \n",
       "811                                  NaN   \n",
       "812                                  NaN   \n",
       "\n",
       "                                            Low Energy Depression State  \n",
       "0    I frequently feel completely exhausted and inc...             Mild  \n",
       "1    I usually feel energized and motivated through...         Moderate  \n",
       "2    I sometimes feel a bit tired, but it doesn't a...           Severe  \n",
       "3    I frequently feel completely exhausted and inc...    No depression  \n",
       "4    I usually feel energized and motivated through...         Moderate  \n",
       "..                                                 ...              ...  \n",
       "808                                                NaN              NaN  \n",
       "809                                                NaN              NaN  \n",
       "810                                                NaN              NaN  \n",
       "811                                                NaN              NaN  \n",
       "812                                                NaN              NaN  \n",
       "\n",
       "[813 rows x 16 columns]"
      ]
     },
     "execution_count": 3,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "data"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "12a0fd60-9932-4560-92c0-fd4a531bad8d",
   "metadata": {},
   "source": [
    "<h1>gotta clean this bruhh</h1>"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "9bdad403-8012-48bd-a1a7-9c99dab03046",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "Number                 0\n",
       "Sleep                290\n",
       "Appetite             273\n",
       "Interest             273\n",
       "Fatigue              290\n",
       "Worthlessness        290\n",
       "Concentration        273\n",
       "Agitation            290\n",
       "Suicidal Ideation    290\n",
       "Sleep Disturbance    273\n",
       "Aggression           290\n",
       "Panic Attacks        290\n",
       "Hopelessness         290\n",
       "Restlessness         290\n",
       "Low Energy           288\n",
       "Depression State     273\n",
       "dtype: int64"
      ]
     },
     "execution_count": 4,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "data.isna().sum()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "690db759-d637-4a9e-b131-e1ff5de8c9e9",
   "metadata": {},
   "outputs": [],
   "source": [
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "92a47003-4a8e-474d-82aa-f9ef1b548eb3",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Total number of entries: 813\n"
     ]
    }
   ],
   "source": [
    "print(\"Total number of entries:\", data.shape[0])\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "08ec37b0-ef43-4f8f-baad-672cd619079f",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Index(['Sleep', 'Appetite', 'Interest', 'Fatigue', 'Worthlessness',\n",
      "       'Concentration', 'Agitation', 'Suicidal Ideation', 'Sleep Disturbance',\n",
      "       'Aggression', 'Panic Attacks', 'Hopelessness', 'Restlessness',\n",
      "       'Low Energy', 'Depression State'],\n",
      "      dtype='object')\n"
     ]
    }
   ],
   "source": [
    "data.columns = data.columns.str.strip()  \n",
    "data = data.drop('Number', axis=1)       \n",
    "\n",
    "print(data.columns)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "35bd787f-0b90-419f-a29f-5e380decac15",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Total number of entries: 813\n"
     ]
    }
   ],
   "source": [
    "print(\"Total number of entries:\", data.shape[0])\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "e5a132c5-055c-4f9b-9bbb-697d327dbc0d",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Number of fully empty rows: 273\n"
     ]
    }
   ],
   "source": [
    "# Step 1: Find fully empty rows\n",
    "empty_rows = data[data.isnull().all(axis=1)]\n",
    "\n",
    "# Step 2: Print how many there are\n",
    "print(\"Number of fully empty rows:\", empty_rows.shape[0])\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "b900900c-9e9d-4ca2-a62c-4c387e7319c1",
   "metadata": {},
   "outputs": [],
   "source": [
    "data = data.dropna(how='all')\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "5c8cbaba-7d78-438e-8cbb-82f0d9da9d11",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Sleep</th>\n",
       "      <th>Appetite</th>\n",
       "      <th>Interest</th>\n",
       "      <th>Fatigue</th>\n",
       "      <th>Worthlessness</th>\n",
       "      <th>Concentration</th>\n",
       "      <th>Agitation</th>\n",
       "      <th>Suicidal Ideation</th>\n",
       "      <th>Sleep Disturbance</th>\n",
       "      <th>Aggression</th>\n",
       "      <th>Panic Attacks</th>\n",
       "      <th>Hopelessness</th>\n",
       "      <th>Restlessness</th>\n",
       "      <th>Low Energy</th>\n",
       "      <th>Depression State</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>535</th>\n",
       "      <td>3–5 hours</td>\n",
       "      <td>Significantly increased</td>\n",
       "      <td>I feel completely disengaged and indifferent t...</td>\n",
       "      <td>I feel energized and capable most of the time</td>\n",
       "      <td>I generally feel confident and worthwhile</td>\n",
       "      <td>Concentration is almost impossible, and I feel...</td>\n",
       "      <td>I feel calm and settled</td>\n",
       "      <td>Never</td>\n",
       "      <td>Barely sleep at all anymore</td>\n",
       "      <td>Very calm</td>\n",
       "      <td>Never happens</td>\n",
       "      <td>Almost never – I usually feel hopeful</td>\n",
       "      <td>I feel calm most of the time</td>\n",
       "      <td>I frequently feel completely exhausted and inc...</td>\n",
       "      <td>Mild</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>536</th>\n",
       "      <td>More than 9 hours</td>\n",
       "      <td>Slightly decreased</td>\n",
       "      <td>I notice a dulling of interest sometimes</td>\n",
       "      <td>I sometimes feel drained but manage</td>\n",
       "      <td>I occasionally doubt myself</td>\n",
       "      <td>Distractions sometimes interfere with my focus</td>\n",
       "      <td>I sometimes feel restless or fidgety</td>\n",
       "      <td>Once in a blue moon</td>\n",
       "      <td>Occasionally toss and turn</td>\n",
       "      <td>A little irritated sometimes</td>\n",
       "      <td>Rarely, maybe once or twice</td>\n",
       "      <td>Sometimes – I feel stuck now and then</td>\n",
       "      <td>It happens, but not often</td>\n",
       "      <td>I usually feel energized and motivated through...</td>\n",
       "      <td>Severe</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>537</th>\n",
       "      <td>Less than 3 hours</td>\n",
       "      <td>Significantly decreased</td>\n",
       "      <td>I still find joy in my activities</td>\n",
       "      <td>I am frequently exhausted and struggle to get ...</td>\n",
       "      <td>I frequently feel like a failure and question ...</td>\n",
       "      <td>I focus easily and stay engaged</td>\n",
       "      <td>I am frequently overwhelmed by restlessness an...</td>\n",
       "      <td>Pretty much daily</td>\n",
       "      <td>Sleep like a baby</td>\n",
       "      <td>Angry almost every day</td>\n",
       "      <td>Almost every day, out of nowhere</td>\n",
       "      <td>Always – I feel hopeless every day</td>\n",
       "      <td>I constantly feel uneasy or on edge</td>\n",
       "      <td>I sometimes feel a bit tired, but it doesn't a...</td>\n",
       "      <td>No depression</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>538</th>\n",
       "      <td>3–5 hours</td>\n",
       "      <td>Significantly increased</td>\n",
       "      <td>I feel completely disengaged and indifferent t...</td>\n",
       "      <td>I feel energized and capable most of the time</td>\n",
       "      <td>I generally feel confident and worthwhile</td>\n",
       "      <td>Concentration is almost impossible, and I feel...</td>\n",
       "      <td>I feel calm and settled</td>\n",
       "      <td>Never</td>\n",
       "      <td>Barely sleep at all anymore</td>\n",
       "      <td>Very calm</td>\n",
       "      <td>Never happens</td>\n",
       "      <td>Almost never – I usually feel hopeful</td>\n",
       "      <td>I feel calm most of the time</td>\n",
       "      <td>I usually feel energized and motivated through...</td>\n",
       "      <td>Severe</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>539</th>\n",
       "      <td>More than 9 hours</td>\n",
       "      <td>Slightly decreased</td>\n",
       "      <td>I notice a dulling of interest sometimes</td>\n",
       "      <td>I sometimes feel drained but manage</td>\n",
       "      <td>I occasionally doubt myself</td>\n",
       "      <td>Distractions sometimes interfere with my focus</td>\n",
       "      <td>I sometimes feel restless or fidgety</td>\n",
       "      <td>Once in a blue moon</td>\n",
       "      <td>Occasionally toss and turn</td>\n",
       "      <td>A little irritated sometimes</td>\n",
       "      <td>Rarely, maybe once or twice</td>\n",
       "      <td>Sometimes – I feel stuck now and then</td>\n",
       "      <td>It happens, but not often</td>\n",
       "      <td>I sometimes feel a bit tired, but it doesn't a...</td>\n",
       "      <td>Moderate</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "                 Sleep                 Appetite  \\\n",
       "535          3–5 hours  Significantly increased   \n",
       "536  More than 9 hours       Slightly decreased   \n",
       "537  Less than 3 hours  Significantly decreased   \n",
       "538          3–5 hours  Significantly increased   \n",
       "539  More than 9 hours       Slightly decreased   \n",
       "\n",
       "                                              Interest  \\\n",
       "535  I feel completely disengaged and indifferent t...   \n",
       "536           I notice a dulling of interest sometimes   \n",
       "537                  I still find joy in my activities   \n",
       "538  I feel completely disengaged and indifferent t...   \n",
       "539           I notice a dulling of interest sometimes   \n",
       "\n",
       "                                               Fatigue  \\\n",
       "535      I feel energized and capable most of the time   \n",
       "536                I sometimes feel drained but manage   \n",
       "537  I am frequently exhausted and struggle to get ...   \n",
       "538      I feel energized and capable most of the time   \n",
       "539                I sometimes feel drained but manage   \n",
       "\n",
       "                                         Worthlessness  \\\n",
       "535          I generally feel confident and worthwhile   \n",
       "536                        I occasionally doubt myself   \n",
       "537  I frequently feel like a failure and question ...   \n",
       "538          I generally feel confident and worthwhile   \n",
       "539                        I occasionally doubt myself   \n",
       "\n",
       "                                         Concentration  \\\n",
       "535  Concentration is almost impossible, and I feel...   \n",
       "536     Distractions sometimes interfere with my focus   \n",
       "537                    I focus easily and stay engaged   \n",
       "538  Concentration is almost impossible, and I feel...   \n",
       "539     Distractions sometimes interfere with my focus   \n",
       "\n",
       "                                             Agitation    Suicidal Ideation  \\\n",
       "535                            I feel calm and settled                Never   \n",
       "536               I sometimes feel restless or fidgety  Once in a blue moon   \n",
       "537  I am frequently overwhelmed by restlessness an...    Pretty much daily   \n",
       "538                            I feel calm and settled                Never   \n",
       "539               I sometimes feel restless or fidgety  Once in a blue moon   \n",
       "\n",
       "               Sleep Disturbance                    Aggression  \\\n",
       "535  Barely sleep at all anymore                     Very calm   \n",
       "536   Occasionally toss and turn  A little irritated sometimes   \n",
       "537            Sleep like a baby        Angry almost every day   \n",
       "538  Barely sleep at all anymore                     Very calm   \n",
       "539   Occasionally toss and turn  A little irritated sometimes   \n",
       "\n",
       "                        Panic Attacks                           Hopelessness  \\\n",
       "535                     Never happens  Almost never – I usually feel hopeful   \n",
       "536       Rarely, maybe once or twice  Sometimes – I feel stuck now and then   \n",
       "537  Almost every day, out of nowhere     Always – I feel hopeless every day   \n",
       "538                     Never happens  Almost never – I usually feel hopeful   \n",
       "539       Rarely, maybe once or twice  Sometimes – I feel stuck now and then   \n",
       "\n",
       "                            Restlessness  \\\n",
       "535         I feel calm most of the time   \n",
       "536            It happens, but not often   \n",
       "537  I constantly feel uneasy or on edge   \n",
       "538         I feel calm most of the time   \n",
       "539            It happens, but not often   \n",
       "\n",
       "                                            Low Energy Depression State  \n",
       "535  I frequently feel completely exhausted and inc...             Mild  \n",
       "536  I usually feel energized and motivated through...           Severe  \n",
       "537  I sometimes feel a bit tired, but it doesn't a...    No depression  \n",
       "538  I usually feel energized and motivated through...           Severe  \n",
       "539  I sometimes feel a bit tired, but it doesn't a...         Moderate  "
      ]
     },
     "execution_count": 10,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "data.tail()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "075422d1-6989-4452-b10c-9a4d80541c5e",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Sleep                17\n",
      "Appetite              0\n",
      "Interest              0\n",
      "Fatigue              17\n",
      "Worthlessness        17\n",
      "Concentration         0\n",
      "Agitation            17\n",
      "Suicidal Ideation    17\n",
      "Sleep Disturbance     0\n",
      "Aggression           17\n",
      "Panic Attacks        17\n",
      "Hopelessness         17\n",
      "Restlessness         17\n",
      "Low Energy           15\n",
      "Depression State      0\n",
      "dtype: int64\n"
     ]
    }
   ],
   "source": [
    "print(data.isnull().sum())\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "id": "3d948979-2083-49e2-b16f-65e601926c9d",
   "metadata": {},
   "outputs": [],
   "source": [
    "import random\n",
    "import pandas as pd\n",
    "\n",
    "# All your mappings, stored together\n",
    "mappings = {\n",
    "    \"Sleep\": [\n",
    "        \"Less than 3 hours\",\n",
    "        \"3–5 hours\",\n",
    "        \"5–7 hours\",\n",
    "        \"7–9 hours\",\n",
    "        \"More than 9 hours\"\n",
    "    ],\n",
    "    \"Appetite\": [\n",
    "        \"Significantly decreased\",\n",
    "        \"Slightly decreased\",\n",
    "        \"No change\",\n",
    "        \"Slightly increased\",\n",
    "        \"Significantly increased\"\n",
    "    ],\n",
    "    \"Interest\": [\n",
    "        \"I still find joy in my activities\",\n",
    "        \"I notice a dulling of interest sometimes\",\n",
    "        \"Lately, I’ve been feeling disconnected from what I used to enjoy\",\n",
    "        \"I rarely feel motivated or interested anymore\",\n",
    "        \"I feel completely disengaged and indifferent to my activities\"\n",
    "    ],\n",
    "    \"Fatigue\": [\n",
    "        \"I feel energized and capable most of the time\",\n",
    "        \"I sometimes feel drained but manage\",\n",
    "        \"Lately, fatigue has been a persistent challenge for me\",\n",
    "        \"I often feel overwhelmed by exhaustion\",\n",
    "        \"I am frequently exhausted and struggle to get through the day\"\n",
    "    ],\n",
    "    \"Worthlessness\": [\n",
    "        \"I generally feel confident and worthwhile\",\n",
    "        \"I occasionally doubt myself\",\n",
    "        \"Lately, negative feelings about myself have increased\",\n",
    "        \"I often struggle with feelings of worthlessness\",\n",
    "        \"I frequently feel like a failure and question my worth\"\n",
    "    ],\n",
    "    \"Concentration\": [\n",
    "        \"I focus easily and stay engaged\",\n",
    "        \"Distractions sometimes interfere with my focus\",\n",
    "        \"Lately, maintaining concentration has been challenging\",\n",
    "        \"I often feel overwhelmed and unable to focus\",\n",
    "        \"Concentration is almost impossible, and I feel overwhelmed\"\n",
    "    ],\n",
    "    \"Agitation\": [\n",
    "        \"I feel calm and settled\",\n",
    "        \"I sometimes feel restless or fidgety\",\n",
    "        \"Lately, I’ve been feeling more restless than usual\",\n",
    "        \"I often feel anxious, restless, or unable to stay still\",\n",
    "        \"I am frequently overwhelmed by restlessness and agitation\"\n",
    "    ],\n",
    "    \"Suicidal Ideation\": [\n",
    "        \"Never\",\n",
    "        \"Once in a blue moon\",\n",
    "        \"Every now and then\",\n",
    "        \"Almost every week\",\n",
    "        \"Pretty much daily\"\n",
    "    ],\n",
    "    \"Sleep Disturbance\": [\n",
    "        \"Sleep like a baby\",\n",
    "        \"Occasionally toss and turn\",\n",
    "        \"Restless some nights\",\n",
    "        \"Almost every night is a struggle\",\n",
    "        \"Barely sleep at all anymore\"\n",
    "    ],\n",
    "    \"Aggression\": [\n",
    "        \"Very calm\",\n",
    "        \"A little irritated sometimes\",\n",
    "        \"Get angry once in a while\",\n",
    "        \"Feel angry quite often\",\n",
    "        \"Angry almost every day\"\n",
    "    ],\n",
    "    \"Panic Attacks\": [\n",
    "        \"Never happens\",\n",
    "        \"Rarely, maybe once or twice\",\n",
    "        \"Sometimes, depends on the day\",\n",
    "        \"Often, it catches me off guard\",\n",
    "        \"Almost every day, out of nowhere\"\n",
    "    ],\n",
    "    \"Hopelessness\": [\n",
    "        \"Almost never – I usually feel hopeful\",\n",
    "        \"Sometimes – I feel stuck now and then\",\n",
    "        \"Often – I lose hope quite a bit\",\n",
    "        \"Most of the time – I feel things won’t improve\",\n",
    "        \"Always – I feel hopeless every day\"\n",
    "    ],\n",
    "    \"Restlessness\": [\n",
    "        \"I feel calm most of the time\",\n",
    "        \"It happens, but not often\",\n",
    "        \"I do notice it from time to time\",\n",
    "        \"find it hard to stay still or feel settled\",\n",
    "        \"I constantly feel uneasy or on edge\"\n",
    "    ],\n",
    "    \"Low Energy\": [\n",
    "        \"I usually feel energized and motivated throughout the day\",\n",
    "        \"I sometimes feel a bit tired, but it doesn't affect me much\",\n",
    "        \"Lately, I’ve been feeling noticeably drained and sluggish\",\n",
    "        \"I often struggle with low energy, making daily activities difficult\",\n",
    "        \"I frequently feel completely exhausted and incapable of doing what I need to\"\n",
    "    ]\n",
    "}\n",
    "\n",
    "# Function to fill NaNs in each column with random choices from mapping\n",
    "for column, values in mappings.items():\n",
    "    if column in data.columns:\n",
    "        data[column] = data[column].apply(\n",
    "            lambda x: random.choice(values) if pd.isnull(x) else x\n",
    "        )\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "id": "9fe14dab-28c1-4a2f-803b-df61e4c4a166",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Sleep                0\n",
      "Appetite             0\n",
      "Interest             0\n",
      "Fatigue              0\n",
      "Worthlessness        0\n",
      "Concentration        0\n",
      "Agitation            0\n",
      "Suicidal Ideation    0\n",
      "Sleep Disturbance    0\n",
      "Aggression           0\n",
      "Panic Attacks        0\n",
      "Hopelessness         0\n",
      "Restlessness         0\n",
      "Low Energy           0\n",
      "Depression State     0\n",
      "dtype: int64\n"
     ]
    }
   ],
   "source": [
    "print(data.isnull().sum())\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "68e21dc4-064c-4106-893f-70be5c936786",
   "metadata": {},
   "source": [
    "<h1>alright so now as the data is clean , we will begin with encoding , since all the data is ordinal</h1>"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "id": "08c7b3c4-c48d-41dc-8e79-76e9dda46321",
   "metadata": {},
   "outputs": [],
   "source": [
    "\n",
    "\n",
    "# Create a dictionary to hold encoders for each column\n",
    "encoders = {}\n",
    "encoded_data = data.copy()\n",
    "\n",
    "# Apply LabelEncoder to every column\n",
    "for column in encoded_data.columns:\n",
    "    l = LabelEncoder()\n",
    "    encoded_data[column] = l.fit_transform(encoded_data[column])\n",
    "    encoders[column] = l # Save the encoder for later decoding\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "id": "c5b83eb6-14f1-4fee-a022-5832c84323dc",
   "metadata": {},
   "outputs": [],
   "source": [
    "data[\"Total_Score\"] = encoded_data.sum(axis=1)\n",
    "def classify_depression(score):\n",
    "    if score <= 14:\n",
    "        return 'No Depression'\n",
    "    elif score <= 24:\n",
    "        return 'Mild Depression'\n",
    "    elif score <= 34:\n",
    "        return 'Moderate Depression'\n",
    "    elif score <= 44:\n",
    "        return 'Severe Depression'\n",
    "    else:\n",
    "        return 'Extremely Severe'\n",
    "\n",
    "data[\"Depression State\"] = data[\"Total_Score\"].apply(classify_depression)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "id": "26cf451f-2aa9-4e1c-ba23-e693bd782c76",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Sleep</th>\n",
       "      <th>Appetite</th>\n",
       "      <th>Interest</th>\n",
       "      <th>Fatigue</th>\n",
       "      <th>Worthlessness</th>\n",
       "      <th>Concentration</th>\n",
       "      <th>Agitation</th>\n",
       "      <th>Suicidal Ideation</th>\n",
       "      <th>Sleep Disturbance</th>\n",
       "      <th>Aggression</th>\n",
       "      <th>Panic Attacks</th>\n",
       "      <th>Hopelessness</th>\n",
       "      <th>Restlessness</th>\n",
       "      <th>Low Energy</th>\n",
       "      <th>Depression State</th>\n",
       "      <th>Total_Score</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>Less than 3 hours</td>\n",
       "      <td>Significantly decreased</td>\n",
       "      <td>I still find joy in my activities</td>\n",
       "      <td>I am frequently exhausted and struggle to get ...</td>\n",
       "      <td>I frequently feel like a failure and question ...</td>\n",
       "      <td>I focus easily and stay engaged</td>\n",
       "      <td>I am frequently overwhelmed by restlessness an...</td>\n",
       "      <td>Pretty much daily</td>\n",
       "      <td>Sleep like a baby</td>\n",
       "      <td>Angry almost every day</td>\n",
       "      <td>Almost every day, out of nowhere</td>\n",
       "      <td>Always – I feel hopeless every day</td>\n",
       "      <td>I constantly feel uneasy or on edge</td>\n",
       "      <td>I frequently feel completely exhausted and inc...</td>\n",
       "      <td>Moderate Depression</td>\n",
       "      <td>25</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>3–5 hours</td>\n",
       "      <td>Significantly increased</td>\n",
       "      <td>I feel completely disengaged and indifferent t...</td>\n",
       "      <td>I feel energized and capable most of the time</td>\n",
       "      <td>I generally feel confident and worthwhile</td>\n",
       "      <td>Concentration is almost impossible, and I feel...</td>\n",
       "      <td>I feel calm and settled</td>\n",
       "      <td>Never</td>\n",
       "      <td>Barely sleep at all anymore</td>\n",
       "      <td>Very calm</td>\n",
       "      <td>Never happens</td>\n",
       "      <td>Almost never – I usually feel hopeful</td>\n",
       "      <td>I feel calm most of the time</td>\n",
       "      <td>I usually feel energized and motivated through...</td>\n",
       "      <td>Moderate Depression</td>\n",
       "      <td>25</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>More than 9 hours</td>\n",
       "      <td>Slightly decreased</td>\n",
       "      <td>I notice a dulling of interest sometimes</td>\n",
       "      <td>I sometimes feel drained but manage</td>\n",
       "      <td>I occasionally doubt myself</td>\n",
       "      <td>Distractions sometimes interfere with my focus</td>\n",
       "      <td>I sometimes feel restless or fidgety</td>\n",
       "      <td>Once in a blue moon</td>\n",
       "      <td>Occasionally toss and turn</td>\n",
       "      <td>A little irritated sometimes</td>\n",
       "      <td>Rarely, maybe once or twice</td>\n",
       "      <td>Sometimes – I feel stuck now and then</td>\n",
       "      <td>It happens, but not often</td>\n",
       "      <td>I sometimes feel a bit tired, but it doesn't a...</td>\n",
       "      <td>Severe Depression</td>\n",
       "      <td>43</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>Less than 3 hours</td>\n",
       "      <td>Significantly decreased</td>\n",
       "      <td>I still find joy in my activities</td>\n",
       "      <td>I am frequently exhausted and struggle to get ...</td>\n",
       "      <td>I frequently feel like a failure and question ...</td>\n",
       "      <td>I focus easily and stay engaged</td>\n",
       "      <td>I am frequently overwhelmed by restlessness an...</td>\n",
       "      <td>Pretty much daily</td>\n",
       "      <td>Sleep like a baby</td>\n",
       "      <td>Angry almost every day</td>\n",
       "      <td>Almost every day, out of nowhere</td>\n",
       "      <td>Always – I feel hopeless every day</td>\n",
       "      <td>I constantly feel uneasy or on edge</td>\n",
       "      <td>I frequently feel completely exhausted and inc...</td>\n",
       "      <td>Moderate Depression</td>\n",
       "      <td>27</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>3–5 hours</td>\n",
       "      <td>Significantly increased</td>\n",
       "      <td>I feel completely disengaged and indifferent t...</td>\n",
       "      <td>I feel energized and capable most of the time</td>\n",
       "      <td>I generally feel confident and worthwhile</td>\n",
       "      <td>Concentration is almost impossible, and I feel...</td>\n",
       "      <td>I feel calm and settled</td>\n",
       "      <td>Never</td>\n",
       "      <td>Barely sleep at all anymore</td>\n",
       "      <td>Very calm</td>\n",
       "      <td>Never happens</td>\n",
       "      <td>Almost never – I usually feel hopeful</td>\n",
       "      <td>I feel calm most of the time</td>\n",
       "      <td>I usually feel energized and motivated through...</td>\n",
       "      <td>Moderate Depression</td>\n",
       "      <td>25</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "               Sleep                 Appetite  \\\n",
       "0  Less than 3 hours  Significantly decreased   \n",
       "1          3–5 hours  Significantly increased   \n",
       "2  More than 9 hours       Slightly decreased   \n",
       "3  Less than 3 hours  Significantly decreased   \n",
       "4          3–5 hours  Significantly increased   \n",
       "\n",
       "                                            Interest  \\\n",
       "0                  I still find joy in my activities   \n",
       "1  I feel completely disengaged and indifferent t...   \n",
       "2           I notice a dulling of interest sometimes   \n",
       "3                  I still find joy in my activities   \n",
       "4  I feel completely disengaged and indifferent t...   \n",
       "\n",
       "                                             Fatigue  \\\n",
       "0  I am frequently exhausted and struggle to get ...   \n",
       "1      I feel energized and capable most of the time   \n",
       "2                I sometimes feel drained but manage   \n",
       "3  I am frequently exhausted and struggle to get ...   \n",
       "4      I feel energized and capable most of the time   \n",
       "\n",
       "                                       Worthlessness  \\\n",
       "0  I frequently feel like a failure and question ...   \n",
       "1          I generally feel confident and worthwhile   \n",
       "2                        I occasionally doubt myself   \n",
       "3  I frequently feel like a failure and question ...   \n",
       "4          I generally feel confident and worthwhile   \n",
       "\n",
       "                                       Concentration  \\\n",
       "0                    I focus easily and stay engaged   \n",
       "1  Concentration is almost impossible, and I feel...   \n",
       "2     Distractions sometimes interfere with my focus   \n",
       "3                    I focus easily and stay engaged   \n",
       "4  Concentration is almost impossible, and I feel...   \n",
       "\n",
       "                                           Agitation    Suicidal Ideation  \\\n",
       "0  I am frequently overwhelmed by restlessness an...    Pretty much daily   \n",
       "1                            I feel calm and settled                Never   \n",
       "2               I sometimes feel restless or fidgety  Once in a blue moon   \n",
       "3  I am frequently overwhelmed by restlessness an...    Pretty much daily   \n",
       "4                            I feel calm and settled                Never   \n",
       "\n",
       "             Sleep Disturbance                    Aggression  \\\n",
       "0            Sleep like a baby        Angry almost every day   \n",
       "1  Barely sleep at all anymore                     Very calm   \n",
       "2   Occasionally toss and turn  A little irritated sometimes   \n",
       "3            Sleep like a baby        Angry almost every day   \n",
       "4  Barely sleep at all anymore                     Very calm   \n",
       "\n",
       "                      Panic Attacks                           Hopelessness  \\\n",
       "0  Almost every day, out of nowhere     Always – I feel hopeless every day   \n",
       "1                     Never happens  Almost never – I usually feel hopeful   \n",
       "2       Rarely, maybe once or twice  Sometimes – I feel stuck now and then   \n",
       "3  Almost every day, out of nowhere     Always – I feel hopeless every day   \n",
       "4                     Never happens  Almost never – I usually feel hopeful   \n",
       "\n",
       "                          Restlessness  \\\n",
       "0  I constantly feel uneasy or on edge   \n",
       "1         I feel calm most of the time   \n",
       "2            It happens, but not often   \n",
       "3  I constantly feel uneasy or on edge   \n",
       "4         I feel calm most of the time   \n",
       "\n",
       "                                          Low Energy     Depression State  \\\n",
       "0  I frequently feel completely exhausted and inc...  Moderate Depression   \n",
       "1  I usually feel energized and motivated through...  Moderate Depression   \n",
       "2  I sometimes feel a bit tired, but it doesn't a...    Severe Depression   \n",
       "3  I frequently feel completely exhausted and inc...  Moderate Depression   \n",
       "4  I usually feel energized and motivated through...  Moderate Depression   \n",
       "\n",
       "   Total_Score  \n",
       "0           25  \n",
       "1           25  \n",
       "2           43  \n",
       "3           27  \n",
       "4           25  "
      ]
     },
     "execution_count": 16,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "data.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "id": "86385c45-9799-4f9e-8444-04f6779969f0",
   "metadata": {},
   "outputs": [],
   "source": [
    "\n",
    "\n",
    "# Create a dictionary to hold encoders for each column\n",
    "New = {}\n",
    "new_data = data.copy()\n",
    "\n",
    "# Apply LabelEncoder to every column\n",
    "for column in new_data.columns:\n",
    "    le = LabelEncoder()\n",
    "    new_data[column] = le.fit_transform(new_data[column])\n",
    "    New[column] = le  # Save the encoder for later decoding\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "id": "fb97407b-d5aa-4e15-afbf-814961c2868f",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Sleep</th>\n",
       "      <th>Appetite</th>\n",
       "      <th>Interest</th>\n",
       "      <th>Fatigue</th>\n",
       "      <th>Worthlessness</th>\n",
       "      <th>Concentration</th>\n",
       "      <th>Agitation</th>\n",
       "      <th>Suicidal Ideation</th>\n",
       "      <th>Sleep Disturbance</th>\n",
       "      <th>Aggression</th>\n",
       "      <th>Panic Attacks</th>\n",
       "      <th>Hopelessness</th>\n",
       "      <th>Restlessness</th>\n",
       "      <th>Low Energy</th>\n",
       "      <th>Depression State</th>\n",
       "      <th>Total_Score</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>3</td>\n",
       "      <td>1</td>\n",
       "      <td>3</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>2</td>\n",
       "      <td>0</td>\n",
       "      <td>4</td>\n",
       "      <td>4</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>2</td>\n",
       "      <td>9</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>0</td>\n",
       "      <td>2</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>2</td>\n",
       "      <td>1</td>\n",
       "      <td>4</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>2</td>\n",
       "      <td>3</td>\n",
       "      <td>2</td>\n",
       "      <td>9</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>4</td>\n",
       "      <td>3</td>\n",
       "      <td>1</td>\n",
       "      <td>3</td>\n",
       "      <td>2</td>\n",
       "      <td>1</td>\n",
       "      <td>3</td>\n",
       "      <td>3</td>\n",
       "      <td>2</td>\n",
       "      <td>0</td>\n",
       "      <td>3</td>\n",
       "      <td>4</td>\n",
       "      <td>3</td>\n",
       "      <td>2</td>\n",
       "      <td>3</td>\n",
       "      <td>26</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>3</td>\n",
       "      <td>1</td>\n",
       "      <td>3</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>2</td>\n",
       "      <td>0</td>\n",
       "      <td>4</td>\n",
       "      <td>4</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>2</td>\n",
       "      <td>11</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>0</td>\n",
       "      <td>2</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>2</td>\n",
       "      <td>1</td>\n",
       "      <td>4</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>2</td>\n",
       "      <td>3</td>\n",
       "      <td>2</td>\n",
       "      <td>9</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "   Sleep  Appetite  Interest  Fatigue  Worthlessness  Concentration  \\\n",
       "0      3         1         3        0              0              2   \n",
       "1      0         2         0        1              1              0   \n",
       "2      4         3         1        3              2              1   \n",
       "3      3         1         3        0              0              2   \n",
       "4      0         2         0        1              1              0   \n",
       "\n",
       "   Agitation  Suicidal Ideation  Sleep Disturbance  Aggression  Panic Attacks  \\\n",
       "0          0                  4                  4           1              0   \n",
       "1          1                  2                  1           4              1   \n",
       "2          3                  3                  2           0              3   \n",
       "3          0                  4                  4           1              0   \n",
       "4          1                  2                  1           4              1   \n",
       "\n",
       "   Hopelessness  Restlessness  Low Energy  Depression State  Total_Score  \n",
       "0             1             0           0                 2            9  \n",
       "1             0             2           3                 2            9  \n",
       "2             4             3           2                 3           26  \n",
       "3             1             0           0                 2           11  \n",
       "4             0             2           3                 2            9  "
      ]
     },
     "execution_count": 18,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "new_data.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "id": "1faa39ae-3e16-4f38-a5a4-377091ff11ed",
   "metadata": {},
   "outputs": [],
   "source": [
    "# X = all columns except target\n",
    "X = new_data.drop('Depression State', axis=1)\n",
    "\n",
    "# y = the target column\n",
    "y = new_data['Depression State']\n",
    "\n",
    "# Encode y\n",
    "target_encoder = LabelEncoder()\n",
    "y_encoded = target_encoder.fit_transform(y)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "id": "60239f57-da0d-461e-ad43-400a5d3363ca",
   "metadata": {},
   "outputs": [],
   "source": [
    "from sklearn.model_selection import train_test_split\n",
    "\n",
    "X_train, X_test, y_train, y_test = train_test_split(X, y_encoded, test_size=0.3, random_state=42)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 21,
   "id": "98e4d433-1bcb-4706-a5c1-960dc93c2583",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "📊 Random Forest Results:\n",
      "Accuracy: 0.9876543209876543\n",
      "              precision    recall  f1-score   support\n",
      "\n",
      "           0       1.00      1.00      1.00         6\n",
      "           1       1.00      1.00      1.00        34\n",
      "           2       0.99      0.99      0.99        68\n",
      "           3       0.98      0.98      0.98        54\n",
      "\n",
      "    accuracy                           0.99       162\n",
      "   macro avg       0.99      0.99      0.99       162\n",
      "weighted avg       0.99      0.99      0.99       162\n",
      "\n",
      "\n",
      "📊 Logistic Regression Results:\n",
      "Accuracy: 0.9814814814814815\n",
      "              precision    recall  f1-score   support\n",
      "\n",
      "           0       1.00      1.00      1.00         6\n",
      "           1       1.00      1.00      1.00        34\n",
      "           2       1.00      0.96      0.98        68\n",
      "           3       0.95      1.00      0.97        54\n",
      "\n",
      "    accuracy                           0.98       162\n",
      "   macro avg       0.99      0.99      0.99       162\n",
      "weighted avg       0.98      0.98      0.98       162\n",
      "\n"
     ]
    }
   ],
   "source": [
    "# 1️⃣ Random Forest Classifier\n",
    "rf_model = RandomForestClassifier(random_state=42)\n",
    "rf_model.fit(X_train, y_train)\n",
    "rf_preds = rf_model.predict(X_test)\n",
    "\n",
    "print(\"📊 Random Forest Results:\")\n",
    "print(\"Accuracy:\", accuracy_score(y_test, rf_preds))\n",
    "print(classification_report(y_test, rf_preds))\n",
    "\n",
    "# 2️⃣ Logistic Regression\n",
    "log_model = LogisticRegression(max_iter=1000)  # max_iter increased for convergence\n",
    "log_model.fit(X_train, y_train)\n",
    "log_preds = log_model.predict(X_test)\n",
    "\n",
    "print(\"\\n📊 Logistic Regression Results:\")\n",
    "print(\"Accuracy:\", accuracy_score(y_test, log_preds))\n",
    "print(classification_report(y_test, log_preds))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "da660b5b-5081-4dd3-9a1c-0016af34de8a",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
